apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pa-dev-architecture

helmGlobals:
   chartHome: ../../base


helmCharts:
  - name: example
    releaseName: my-release
    namespace: default
    valuesFile: values.yaml



